CREATE DATABASE IF NOT EXISTS eventease_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE eventease_db;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS payments,registrations,tickets,event_schedules,venue_bookings,events,venues,categories,notifications,reviews,users;
SET FOREIGN_KEY_CHECKS=1;
CREATE TABLE users(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,email VARCHAR(150) NOT NULL UNIQUE,phone VARCHAR(30),password VARCHAR(255) NOT NULL,role ENUM('admin','organizer','participant') DEFAULT 'participant',profile_image VARCHAR(255),status ENUM('active','suspended') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE categories(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,slug VARCHAR(120),description TEXT,icon VARCHAR(100),image VARCHAR(255),status ENUM('active','inactive') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE venues(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150) NOT NULL,type VARCHAR(100),location VARCHAR(255),capacity INT DEFAULT 0,price DECIMAL(12,2) DEFAULT 0,description TEXT,image VARCHAR(255),status ENUM('active','inactive') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE events(id INT AUTO_INCREMENT PRIMARY KEY,organizer_id INT NOT NULL,category_id INT,venue_id INT NULL,title VARCHAR(200) NOT NULL,slug VARCHAR(220),description TEXT,start_date DATE NOT NULL,end_date DATE,start_time TIME,end_time TIME,location VARCHAR(255),max_participants INT DEFAULT 0,image VARCHAR(255),status ENUM('pending','approved','rejected','completed','cancelled') DEFAULT 'pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(organizer_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE SET NULL,FOREIGN KEY(venue_id) REFERENCES venues(id) ON DELETE SET NULL);
CREATE TABLE event_schedules(id INT AUTO_INCREMENT PRIMARY KEY,event_id INT NOT NULL,title VARCHAR(200),description TEXT,schedule_date DATE,start_time TIME,end_time TIME,FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE);
CREATE TABLE tickets(id INT AUTO_INCREMENT PRIMARY KEY,event_id INT NOT NULL,name VARCHAR(100) NOT NULL,price DECIMAL(12,2) DEFAULT 0,quantity INT DEFAULT 0,available_quantity INT DEFAULT 0,description TEXT,FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE);
CREATE TABLE registrations(id INT AUTO_INCREMENT PRIMARY KEY,event_id INT NOT NULL,user_id INT NOT NULL,ticket_id INT NOT NULL,registration_code VARCHAR(80) UNIQUE,quantity INT DEFAULT 1,total_amount DECIMAL(12,2) DEFAULT 0,status ENUM('pending','confirmed','cancelled') DEFAULT 'pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(ticket_id) REFERENCES tickets(id) ON DELETE CASCADE);
CREATE TABLE payments(id INT AUTO_INCREMENT PRIMARY KEY,registration_id INT NOT NULL,amount DECIMAL(12,2),payment_method VARCHAR(50),transaction_id VARCHAR(100),payment_status ENUM('pending','paid','failed','refunded') DEFAULT 'pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(registration_id) REFERENCES registrations(id) ON DELETE CASCADE);
CREATE TABLE venue_bookings(id INT AUTO_INCREMENT PRIMARY KEY,venue_id INT NOT NULL,organizer_id INT NOT NULL,event_id INT NULL,booking_date DATE,start_time TIME,end_time TIME,total_price DECIMAL(12,2),status ENUM('pending','approved','confirmed','cancelled','completed') DEFAULT 'pending',FOREIGN KEY(venue_id) REFERENCES venues(id),FOREIGN KEY(organizer_id) REFERENCES users(id),FOREIGN KEY(event_id) REFERENCES events(id));
CREATE TABLE notifications(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,title VARCHAR(200),message TEXT,type VARCHAR(50),is_read TINYINT(1) DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE reviews(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,event_id INT NULL,venue_id INT NULL,rating TINYINT,comment TEXT,status ENUM('pending','approved') DEFAULT 'pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
INSERT INTO users(name,email,phone,password,role,status) VALUES
('System Admin','admin@eventease.com','03000000000','$2y$10$7e8r9qjZ1yVDH/5m8aCMcOyZi3h1Hn0BfGQTPPXU.J0dzBcH4nQhu','admin','active'),
('Demo Organizer','organizer@eventease.com','03000000001','$2y$10$7e8r9qjZ1yVDH/5m8aCMcOyZi3h1Hn0BfGQTPPXU.J0dzBcH4nQhu','organizer','active'),
('Demo Participant','user@eventease.com','03000000002','$2y$10$7e8r9qjZ1yVDH/5m8aCMcOyZi3h1Hn0BfGQTPPXU.J0dzBcH4nQhu','participant','active');
INSERT INTO categories(name,slug,description) VALUES
('Education','education','Seminars, workshops and training events'),('Business','business','Conferences and professional meetings'),('Social','social','Weddings, birthdays and celebrations'),('Entertainment','entertainment','Concerts and festivals'),('Competition','competition','Sports, gaming and competitions'),('Wedding','wedding','Wedding events and venues');
INSERT INTO venues(name,type,location,capacity,price,description,status) VALUES
('Royal Wedding Hall','Wedding Hall','Multan',500,100000,'Premium wedding venue','active'),('Grand Conference Center','Conference Hall','Multan',300,75000,'Modern conference venue','active'),('Garden Event Space','Outdoor','Multan',700,90000,'Outdoor celebrations and festivals','active');
INSERT INTO events(organizer_id,category_id,title,description,start_date,end_date,start_time,end_time,location,max_participants,status) VALUES
(2,1,'Technology Conference 2026','A professional technology conference featuring innovation, AI and software development.','2026-10-20','2026-10-20','10:00:00','18:00:00','Multan',300,'approved'),
(2,4,'Music & Culture Festival','A memorable evening of music and culture.','2026-11-05','2026-11-05','17:00:00','23:00:00','Multan',500,'approved');
INSERT INTO tickets(event_id,name,price,quantity,available_quantity,description) VALUES
(1,'Standard',1500,250,250,'Standard conference access'),(1,'VIP',3500,50,50,'VIP conference access'),(2,'General',2000,500,500,'Festival entry');
